### PR TITLE
Resolves issue https://github.com/bridgefoundry/bridgefoundry.github.io/issues/11

### PR DESCRIPTION
**Pull request by PamelaCoupar**

### CODE REVIEW

**Comment by ultrasaurus** [comment]
@stuartblair sorry for the delayed response.... the challenge is that I often want someone to review a draft who might not be a ruby / jekyll developer or even if they are, they might just have time to read on their phone -- sending a link to the draft on the live site has been valuable.

**Comment by ultrasaurus** [comment]
@stuartblair @PamelaCoupar ping?

**Comment by PamelaCoupar** [comment]
Hi Sarah,
Sorry we haven't looked at it for a while. There doesn't appear to be a clean way to do it but we can look at it this week.
Pamela 


    On Saturday, 21 November 2015, 13:57, Sarah Allen <notifications@github.com> wrote:
 

 @stuartblair @PamelaCoupar ping?—

**Comment by PamelaCoupar** [comment]
Hi Sarah,

How attached are you to the front matter variable draft:true. I was wondering about maybe using tags instead and tagging the posts to be shown as tags: ready (or some other tag value).

Pamela

**Comment by ultrasaurus** [comment]
I'm open to that idea.  Not attached to the front matter implementation, only attached to the idea that there is a way to preview drafts on the live site (and just not have them visible to normal browsers).

**Comment by ultrasaurus** [comment]
closing in favor of:  https://github.com/bridgefoundry/bridgefoundry.github.io/pull/24

**Pull request closed without merging**
