### PR TITLE
add board members

### PR DESCRIPTION
**Pull request by ultrasaurus**

### CODE REVIEW

**Comment by ultrasaurus** [comment]
Please :+1: or comment on this:
@durhamka
@BridgetHillyer
@sarahmei
@rachelmyers

**Comment by ultrasaurus** [comment]
@BridgetHillyer sorry about that -- pls review my fix!

**Comment by bridgethillyer** [comment]
:+1:

**Comment by sarahmei** [comment]
:+1:

**Comment by durhamka** [comment]
Looks good!

**Comment by rachelmyers** [comment]
:+1:

**Pull request merged**
