### PR TITLE
Add link to Get Involved header

### LINKED ISSUE #39: Link first sentence of Get Involved to Bridgetroll
sentence to link: Volunteer for a workshop near you.
link: https://www.bridgetroll.org/

### PR DESCRIPTION
**Pull request by audiodude**
Exactly what it says on the tin.

Screenshot: https://www.dropbox.com/s/825l2vjze0hm0n2/Screenshot%202016-02-19%2019.39.56.png?dl=0

Fixes #39.

### CODE REVIEW

**Comment by ultrasaurus** [comment]
actually, it was the first sentence that needs to be linked "Volunteer for a workshop near you"  -- Bridge Troll is just for workshops.  Isa is working on a form for other ways to get involved.

**Comment by audiodude** [comment]
Oops, I guess I read that wrong. I'll fix it.

**Comment by audiodude** [comment]
Okay updated:

https://www.dropbox.com/s/lst704h15hi9xy7/Screenshot%202016-02-20%2008.42.41.png?dl=0

**Comment by ultrasaurus** [comment]
image

**Comment by ultrasaurus** [comment]
wonderful.  thanks @audiodude

**Pull request merged**
