### PR TITLE
New page: History & Where we are now + Nav links

### LINKED ISSUE #29: About > History
Goal: create a page that talks about RailsBridge's origin stories, and how we got to making BridgeFoundry.

current content:
------------------------
------------------------

### How we got started
In June 2009, the [San Francisco Ruby community] (http://www.sfruby.info/) stood at about 97% men, and 3% women. At the time 20% of software developers were women, so we estimated that there were more women developers than there were Ruby developers.  Sarah Mei and Sarah Allen started with a simple hypothesis: if we taught women Ruby, there would be more women Ruby developers.  Our approach was to offer a free workshop teaching Ruby on Rails.  Inspired by Women 2.0, men could participate as student as a guest of a woman.  In order to meet the incredible demand for the workshops, anyone could be a teacher, TA or other volunteer support person.  At our first workshop with had 8 teachers -- 4 women, 4 men and a dad volunteered to supervise the kids play area.

We decided to teach monthly workshops for 1 year.  Teaching 10-20 women per month, if 10% stayed in the community, we would triple the number of women in the community and we estimated that we would reach 20% women at in-person gatherings (meetups and local conferences) in a year.

The first workshop was intended have a maximum of 40 students, but after two tweets and one mailing list post, we had a waiting list in less than 24 hours.  Orange Labs offered their large office space with 8 conference rooms.  By enlisting men as well as women to teach and TA, we were able to expand the capacity to 80, and 62 students participating in an overwhelmingly successful first event.  

With such huge demand and plenty of offers of large office space to hold events, we held large 50 student events every other month.  In less than 6 months, we had met our goal of 20% women at SF Ruby Meetup events.  Additionally, we noticed other significant impact on our local community:  more meetup events, more events targeted at less experienced engineers  and more experienced women Ruby developers coming to events.  We were also building a core team of dedicated volunteer leaders and a perpetually renewing group of volunteer teachers and TAs.  During that first year, we also proved that this would scale across geographies with workshops in Cambridge, MA and Oahu, HI.  We developed open source curriculum and installation instructions that improved with every workshop.

### Developing an Organization to Support a Movement
We documented the [process of organizing a workshop](http://railsbridge.org/help/organize), developed [teacher training](http://docs.railsbridge.org/workshop/more_teacher_training) to encourage more students to become teachers, and [evolved the curriculum](http://docs.railsbridge.org/workshop/) using open source processes and frequent iterations.  In May 2010, a workshop was organized by new leaders for the first time - not just one, but one in San Francisco and one in New York City.  In the subsequent years, the number of workshops has doubled every year, with workshops in 42 cities in 2013, with thriving communities across the globe.

We had decided early on that we would “let nothing get in the way of a workshop happening” when there are students who want to learn, teachers willing to teach, and someone willing to organize an event.   Local companies offered us funding, space, food, etc.  Often all that was needed was someone to connect the people with the resources to the people who wanted to make a workshop happen.  Austin Putman volunteered to be treasurer, with much of his job simply paying $60 for a security guard or $250 for pizza, which worked well for a year or two, but having a single volunteer treasurer is not a sustainable model for a fast-growing organization.

We also had volunteers interested in seeking grants which would require 501c3 status, and individuals who would donate more financially if it could be tax deductible.  We decided to seek fiscal sponsorship as a path to non-profit status.  In 2013, we chose School Factory as our fiscal sponsor, since they offered advice and mentorship on growing an organization, as well as the potential partnership with any of their 80+ maker spaces for holding workshops.  [RailsBridge](http://railsbridge.org/) had been established as an umbrella group for many like-minded initiatives, including:  TeachingKids, RailsMentors, Rails BugMash, and TestFirst.org.  However, RailsBridge was most known for its workshops, so we decided to rename the parent organization. RailsBridge would focus on holding workshops that teach Ruby and Rails.  We were proud of the many groups who were inspired by our work and spun out their own separate organizations: RailsGirls, PyStar, PyLadies, Scala Workshop, Women Who Code, Learn the Front End, Confident Coding JS, PHPBridge; however, we wanted people who were teaching different tech to different groups to feel like they could join us, so we wanted a name that didn't include the name of a specific technology.  The new organization was named [Bridge Foundry](http://bridgefoundry.org/) -- the place where all the bridges can be made, where each bridge is unique.

### Many Bridges
In 2014, [ClojureBridge](http://www.clojurebridge.org/) and [MobileBridge](https://github.com/mobilebridge) were formed, each focused on separate technologies, following the same RailsBridge workshop model, with open source curriculum and all volunteer process.  In its first year, ClojureBridge held eight workshops, including three in Australia.  MobileBridge started with an iOS workshop, held in San Francisco, followed by one in Hawaii, and more in San Francisco. There are plans for Android too.  In Summer 2015, [GoBridge](http://golangbridge.org/) started with several workshops, an [online forum](https://forum.golangbridge.org/), and an [innovative partner program](https://medium.com/@GolangBridge/go-needs-everyone-s-help-13f74bdf3432#.zbhpmygqd).

### How Bridge Foundry Works
The tools that we use are mostly words (wiki, presentations, curriculum, code-of-conduct) and events (teacher trainings, install fest, teaching workshops, speakers); however, we also are developing software for registration and curriculum wrangling.  Our registration tool, [BridgeTroll](https://www.bridgetroll.org/), allows new organizers to have insight into the prior experience of students, teachers, and TAs.  We’re seeing its power to connect the community across technologies, since today all software developers need to know multiple languages and frameworks.

### PR DESCRIPTION
**Pull request by missherico**
- Added History & Where we are now page 
- Fixed in-page table of contents styling
- Added sections in navbar dropdown

This fixes #29

### CODE REVIEW

**Comment by ultrasaurus** [comment]
Also, I think this would be easier to maintain if it were in markdown.  Thanks for putting this together!

**Comment by missherico** [comment]
Hey hey. Yes I can make it as markdown.  Are we nixing the last section all
together? Or adding it somewhere else?

**Comment by ultrasaurus** [comment]
@missherico maybe make a github issue with the content and we'll figure out where it goes later?

**Comment by missherico** [comment]
Hi @ultrasaurus, here are the updates to the page per your sweep plus refactoring to use Markdown.  I left the anchor tags as-is so our Navbar can hook into it + my preference for links would be to open in a new tab.  LMK if that's ok or if there's a better way.  -Isa

**Comment by ultrasaurus** [comment]
👍

**Pull request merged**
