### PR TITLE
Added blog feature

### PR DESCRIPTION
**Pull request by Vibhuti**
I added tab at the navigation bar for blog which will give list of blogs. And after clicking on the title of a blog it will give the full blog post.
All blog entries are under "_posts " folder following the format of  2011-12-31-new-years-eve-is-awesome.md 
I also added one public folder for css and javascripts for blogs, as it was not taking default bootstrap.
Do let me know if i need to do any modification? or if we have any other better solution.
Note: There are two example blog posts under _posts folder, which we need to delete.

### CODE REVIEW

**Comment by ultrasaurus** [comment]
This is great!  I noticed that the blog link is incorrect on the index page, though it works from about.  Can you fix that?

**Comment by ultrasaurus** [comment]
@Vibhuti ideally the navigation would use a partial, which would address:  https://github.com/bridgefoundry/bridgefoundry.github.io/issues/5

Also, if you wouldn't mind updating the footer, copyright should be 2013-2015 now :)

**Comment by Vibhuti** [comment]
@ultrasaurus Thanks! 
Fixed the issues. Do let me know if anything else needed.

**Comment by ultrasaurus** [comment]
I merged this into a new branch:  https://github.com/bridgefoundry/bridgefoundry.github.io/tree/blog
along with a draft of the first post.  I'll post to the mailing list to see if we can get some volunteer content reviewers, and will write up a few more stories.   Thank you!

**Comment by Vibhuti** [comment]
Great, Thanks!

**Pull request closed without merging**
